### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_1#2]
1. Блоки должны быть реализованы в виде миксинов. Каждый блок в своей папке со всей своей реализацией, т.е. разметка, стили, картинки, js-файлы должны лежать в папке блока.
2. Имя миксина должно совпадать с именем блока.

**Comment by EvgeniyChuprov** [comment]
1. Папку BEM логичнее назвать blocks
2. Внутри каждого миксина должен лежать только 1 блок который возвращается этим миксином. Имя папки где лежит миксин, имя миксина и имя блока в миксине должны совпадать.
3. Названия блоков должны быть осмысленны. По названию блока должно быть понятно какую функцию он выполняет.
4. Все стили одного блока должны быть в одном месте и отсортированы по порядку их расположения на странице. Стили одного блока не должны влиять на другие блоки.
5. Не использовать инлайн стили если они пришли не из js-файлов. Кроме блока "software"
![Снимок экрана от 2019-11-13 16-09-06](https://user-images.githubusercontent.com/36810364/68766599-370cbd00-0630-11ea-8bbc-4646214751dc.png)
6. На начальной станице у тебя должен быть 1 блок содержащий другие блоки.

**Comment by whiteGloom** [comment]
1. Понятно, исправил.
2. Ок. Но если **одним** миксином отделаться **нельзя** (как мне кажется)? **Пример:** есть блок, у которого есть дочерние элементы с отступами (внешняя геометрия). И в эти элементы вставляются другие блоки. Что-то вроде колонки с контентом. Как тогда это провернуть?
3. Ещё подумаю над ними.
4. Так они и так, вроде, в одном месте.. Имеется ввиду в одном файле?
5. Понятно, исправил.
6. Можно поподробнее? Имеются ввиду импорты блоков?

**Comment by whiteGloom** [comment]
Поменял название блока p → pStyled.
Убрал блок em.

**Comment by EvgeniyChuprov** [comment]
Почитай про [БЭМ](https://ru.bem.info/methodology/quick-start/) и про разбиение на [блоки](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/semantic.md).
Блок - независимый компонент страницы, который может быть повторно использован.
Элемент  - часть блока, которая не может использоваться в отрыве от него. Миксин представляет собой блок по БЭМ. Т.е. на примере блока CONTACT - миксин contact содержит блок Header, блок contact и его элементы. Ты же например .contact__title отдельно использовать не можешь, а header  компонент который можно использовать отдельно.
![image](https://user-images.githubusercontent.com/36810364/68785619-7eef0c80-064f-11ea-880a-2098ba396e23.png)
У тебя же сейчас нет разделения на блоки и элементы, ты по сути все сделал блоками, те же img, em и p + в самом блоке contact ты зачем то делаешь еще один миксин который у тебя выполняет роль элементов блока.
![image](https://user-images.githubusercontent.com/36810364/68786596-19038480-0651-11ea-97af-6915d271e437.png)
Кстати по поводу инклюдов [Пункт 4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)
Вообщем внимательно перечитай БЭМ и стандарты.
По 4 пункту -  да.

**Comment by whiteGloom** [comment]
Второй пункт исправлю утром (и применю фиксы к второму макету).
Не спорю, то количество миксинов, которое у меня — пугает, к тому можно было убрать большую часть из них. Просто не до конца понимаю некоторый момент, возможно завтра уточню.

**Comment by EvgeniyChuprov** [comment]
Прочитай еще эту [статью](https://fullstack-development.gitbook.io/learn/komponentnaya-arkhitektura)

**Comment by whiteGloom** [comment]
Тогда сразу вопрос: нужно ли делить компоненты на примитивы и на блоки (я имею ввиду иерархически)?
**Например:** в этой статье есть ссылка на [репозиторий-пример](https://github.com/krashaen/pugWithWebpack/tree/master/src/components), где компонента `plan` — блок (содержит инклюдом другую компоненту), а компонента `button` — примитив.

**Comment by whiteGloom** [comment]
Кстати, о том моменте, который я не понимаю.
Расписывать всё заново — долго, поэтому, приведу в качестве примера ситуацию из первого макета (ваш макет рассматриваю исключительно потому, что он вам лучше знаком):

У вас был блок [`content`](https://github.com/EvgeniyChuprov/CV/blob/master/src/blocks/content/content.pug), в котором содержалась основная информация сайта.

Колонку, как мне кажется, можно выделить в миксин — колонка теперь блок (почти как у вас, это ни на что не полвияет). У колонки есть элементы (вы, зачем-то каждому добавили отдельный класс, типа `.content__logo`, чего я не понял, так как они ничем, кроме содержимого не отличаются, а оно подаётся миксином).

**Теперь сама проблема:** Что если таких элементов в колонке будет сто? Ничто не препятствует такому повороту. Каждому применять класс типа `.content__logo`, `.content__profile` и т.п? И каждый туда пихать вручную? В цикл их не запихнёшь, т.к. pug, насколько мне известно, не принимает блоки из строки. Через аргументы их тоже не пропихнёшь... Что делать?

**Comment by whiteGloom** [comment]
Я пока начну править элементы, в которых, как мне кажется, я с этой проблемой не столкнусь.

**Comment by whiteGloom** [comment]
Снова к той проблеме. Если описать её словами, то вот что получается: Как сделать объект, в который будут подаваться **заранее неизвестные** элементы (их количество или имена), имея возможность задавать этим элементам внешнюю геометрию?

Например: у нас есть сто блоков. И каждый из них может быть или не быть в неком wrapper'е.

**Comment by EvgeniyChuprov** [comment]
1. На счет классов в content они нужны для позиционирования внутренних блоков, по БЕМ у  блока не должно быть внешней геометрии + паддинги тоже нельзя в этих целях использовать.
2. > Тогда сразу вопрос: нужно ли делить компоненты на примитивы и на блоки (я имею ввиду иерархически)?

Тут не понял тебя. Может ли блок содержать другой блок? Да. Или что то другое спрашивал?

3. Зачем такое разделение на блоки? Что у тебя делает блок contacts? Сможет он у тебя отдельно использоваться или это все таки элемент чего то большего? А тут - contactsEl - у тебя даже в названии указано что это элементы.
![Снимок экрана от 2019-11-14 13-04-36](https://user-images.githubusercontent.com/36810364/68847848-611db800-06e0-11ea-80fc-2e7537451a0f.png)
С остальными блоками так же.

4. > Снова к той проблеме. Если описать её словами, то вот что получается: Как сделать объект, в который будут подаваться заранее неизвестные элементы (их количество или имена), имея возможность задавать этим элементам внешнюю геометрию?

Тоже не совсем понятен вопрос. Если нужна возможность добавить заранее неизвестное количество элементов - используй циклы например как у меня в блоках skills или education.

**Comment by whiteGloom** [comment]
1. Знаю. Я про то, что, как мне кажется, их можно было обозвать одним классом.
2. Та мне просто было интересно. Не очень понятно в сплошном списке блоков — какой может использоваться отдельно (примитив), а какой в итоге что-то другое использует.. Просто, например, если я перемещу в другую директорию какой-нибудь button, ему будет хорошо, а вот блоку, который его инклюдит - нет.
3. contactsEl я уже убрал.
4. Сейчас посмотрю.

**Comment by whiteGloom** [comment]
2. Обновил комментарий.
4. Не, не совсем то. Я хз, как объяснить текстом) Сейчас что-нибудь придумаю...

**Comment by EvgeniyChuprov** [comment]
> Просто, например, если я перемещу в другую директорию какой-нибудь button, ему будет хорошо, а вот блоку, который его инклюдит - нет.

Поэтому все блоки лежат каждый в своей директории. И блок содержащий в себе другие блоки инклюдит их в себя. В результате блок получается полностью независимый от своего местоположения на странице или сайте. Надеюсь понятно объяснил)

**Comment by whiteGloom** [comment]
Ну а если его переименовать? В любом случае — не столь критично.

**Comment by EvgeniyChuprov** [comment]
> Ну а если его переименовать? В любом случае — не столь критично.

Ты про что?

**Comment by whiteGloom** [comment]
Та.. Я предположил, что если переименовать блок, то придётся перешерстить все блоки, которые теоретически могли бы его инклюднуть.. Но, если подумать, перешерстить придётся всё в любом случае.
Так что — не суть.

**Comment by whiteGloom** [comment]
Ну, я ещё подумал над той проблемой.. И, вроде, максимально понятно сформулировал суть:

Те блоки-элементы (на подобие contactsEl) помогали избавиться от инлайнового написания разметки.

**[Пример такой разметки](https://github.com/EvgeniyChuprov/CV/blob/master/src/blocks/content/content.pug):**
![изображение](https://user-images.githubusercontent.com/36995502/68916239-a2bd6a00-0797-11ea-9f0b-0b751da4950f.png)

По факту — **это те же самые миксины элементов, которые были у меня:** 
![изображение](https://user-images.githubusercontent.com/36995502/68919026-0dc06e00-07a3-11ea-9efb-c5d1bca90a14.png)
, только написанные **каждый раз от руки**.

Конечно, в этом нет ничего ужасного, но что будет, если для элементов колонки потребуются модификаторы (и не дай бог модификаторов будет несколько)? Получается куча довольно страшного кода, разбросанного по странице, который каждый раз нужно обслуживать вручную..

Пример всё того же инлайнового кода, но слегка модифицированного:
![изображение](https://user-images.githubusercontent.com/36995502/68916831-43148e00-079a-11ea-90ed-fdffbe21d477.png)

Добавилось **всего 3 модификатора**, а на код уже страшно смотреть.
А ведь таких блоков в колонке может быть очень много..

Нет ли возможности переделать это на более изящный манер?

**Comment by EvgeniyChuprov** [comment]
Давай с начала)
При взгляде на страницу можно сразу выделить отдельные самодостаточные блоки PROFILE, CONTACT, SKILLS... Так же сразу в отдельный блок можно выделить header, содержащий картинку, заголовок и линию. Так вот, на примере PROFILE - он включает в себя блок header и какое то текстовое содержимое. И этот блок мы можем переиспользовать необходимое количество раз, просто передавая на его вход объект содержащий картинку и заголовок для внутреннего блока header и текст для его элемента __text -например. При этом не важно где мы его расположим, внутреннюю разметку ему менять не надо она подстроится под внешние размеры + элементом внешнего блока будет настроено его позиционирование. То же касается остальных блоков.

И того, у тебя должен быть на начальной странице только 1 блок, содержащий внутри себя все остальные блоки, принимающий в себя все настройки и передающий их во внутренние блоки.
Этот внешний блок может позиционировать внутренние блоки своими элементами. В результате пропадет необходимость в модификаторах.
Так понятно или с чем то не согласен?

**Comment by whiteGloom** [comment]
Ну, с начала, так с начала. По порядку.

**Во первых**  — не согласен с таким выделением блоков: блоки CONTACT, SKILLS и др. **ничем** не отличаются — у всех них присутствует хедер и содержимое.
Это прекрасно видно на примере разделов EDUCATION и EXPIRIENCE — они **вообще ничем** кроме заголовка не отличаются. Оба содержа одинаковые списки. Зачем ИХ выделять в отдельный блок?

**Comment by whiteGloom** [comment]
Об это говорится в статье, которую **Вы же** мне и скинули:
![изображение](https://user-images.githubusercontent.com/36995502/68934436-483d0180-07c9-11ea-8046-db278b14f1a5.png)

**Comment by EvgeniyChuprov** [comment]
> Во первых — не согласен с таким выделением блоков: блоки CONTACT, SKILLS и др. ничем не отличаются — у всех них присутствует хедер и содержимое.

Ну так содержимое то у них разное. Что будет если данные для skills передать в contact и наоборот? Тот же пример с experience и education. Можешь реализовать их как отдельный блок и передавать в него разные данные в его формате, отображение не нарушится. То же и хедером, ты же видишь, в него как в блок хедер можно передать любую пару картинка текст и он будет прекрасно работать. 
Смотри на объекты более глобально.

> Об это говорится в статье, которую Вы же мне и скинули:

  Да 3 блока. Каждый из этих блоков можно расположить отдельно на другой странице или продублировать на этой и он будет продолжать смотреться органично и закончено. Тот же 2 блок можно использовать целиком на этой же странице передав в него другие данные в карточки ну и  изменить количество карточек.

И еще раз
![image](https://user-images.githubusercontent.com/36810364/68942693-4881d080-07ba-11ea-808e-f5b33f939b9a.png)
Блок rate должен физически находиться внутри блока block. А block должен инклюдить внутри себя rate, получать объект с настройками снаружи для себя и rate. Так для всех блоков.
И все блоки у тебя должны лежать внутри одного корневого блока, который получает общий объект параметров и передает их во внутрь.

**Comment by whiteGloom** [comment]
Хорошо. Мы наконец-то примерно друг друга поняли. Так и сделаю. Как закончу, напишу замечания по этой системе)

**Comment by whiteGloom** [comment]
https://github.com/whiteGloom/Response-for-task-2_1/commit/da222483a4799d0c6a206efce61521bb1ea01310
Вот, обновил. Вроде должно быть нормально.

**Comment by whiteGloom** [comment]
**Много букав, но прошу прочитать до конца. Я думаю, эту будет полезно нам обоим.**

Мы с Вами ходили вокруг примерно одного и того же решения, но друг друга не понимали.
В итоге я сделал, как мне кажется, идеальную комбинацию наших с Вами решений.

По порядку:

------------

**Что сделал?**
Я реализовал блоки "profile", "contact", "skills" и т.д. **как пресеты настроек** для общей модели блока.

Такое решение, по идее, соответствует вашим требования:
• улучшает реюзабельность;
• упрощает передачу параметров внутрь;
• исключает случайное вторжение в настройку блока;

Но и удовлетворяет мои:
• в таком решении отсутствуют лишние классы (в вашем макете стили у каждого блока были отдельными, несмотря на то, что были одинаковыми), так как эти пресеты основаны на одной и той же модели;

В итоге блоки получились такими (на примере "skills"):
![изображение](https://user-images.githubusercontent.com/36995502/68988189-26de2300-0866-11ea-924b-d86f8d18b4a4.png)

------------


**Мнение об этой концепции в целом.**
Такое разделение на блоки, как мне кажется, **не является обязательным** требованием и необходимо в том случае, если блоки явно будут использоваться в другом месте **ИЛИ** в том случает, если вы хотите **явно** запечь блок.
Для одиночных вариантов блоков можно использовать и моё предыдущее решение (ниже будет пример), не создавая лишние блоки, которые теоретически могут использоваться отдельно, но никогда не будут.

Главное здесь — не переборщить с такой "глобализацией" блоков:

![изображение](https://user-images.githubusercontent.com/36995502/68988315-bafcba00-0867-11ea-8418-cc13a4958e05.png)

Так как: 
• во первых — можно увлечься и начать объединять в блоки вообще всё подряд.
• во вторых — у вас, хоть и были реализованы блоки, вы не заметили, что эти самые блоки построены по общей схеме, за счёт чего их можно довольно сильно оптимизировать.

------------

**Насчёт вопроса: "Что будет если данные для skills передать в contact и наоборот?"**

Моё предыдущее решение (которое было без разделения на такие блоки) всё так же прекрасно работало бы. Никакой проблемы при передаче данных в другой блок не было бы.

Вот пример:
![изображение](https://user-images.githubusercontent.com/36995502/68988468-acfc6880-086a-11ea-88b8-22c8a7e254d2.png)

Думаю, тут заметно, что тут, по сути, всё точно так же, как и с разделением на блоки: нет никаких случайных передач данных в блок. Просто тут чуть менее очевидна возможность реиспользования. И то — только потому, что это я сейчас **так** это изобразил.

**Comment by whiteGloom** [comment]
Мне сейчас осталось сделать передачу данных из внешнего блока и исправить тег блока content.

**Comment by EvgeniyChuprov** [comment]
Сейчас в принципе хорошо. Тут вроде как основное все. Единственное общий объект настроек должен приходить в content и из него раскидываться дальше.
Переходи ко второму проекту и применяй к нему замечания из этого. Как будешь готов пиши. 

upd
> Такое разделение на блоки, как мне кажется, не является обязательным требованием

На счет этого позже напишу)

**Comment by whiteGloom** [comment]
@EvgeniyChuprov Так, вроде перенёс замечания во второй проект.

**Comment by EvgeniyChuprov** [comment]
Блок внутри блока. Column должен быть либо отдельным блоком, либо элементом блока content
![Снимок экрана от 2019-11-26 12-48-46](https://user-images.githubusercontent.com/36810364/69618553-222a2380-104b-11ea-899b-b5fb06a3827b.png)
