### ISSUE TITLE
Проверить отображение элементов.

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_1#5]
Проверить отображение элементов при разном разрешении.
![image](https://user-images.githubusercontent.com/36810364/68849786-c1622900-06e3-11ea-8325-9e723bf9e485.png)

**Comment by whiteGloom** [comment]
Странно. У меня ничего.. Сейчас разберусь.

**Comment by whiteGloom** [comment]
Вроде пофиксил. GHPages скоро обновится.

**Comment by whiteGloom** [comment]
Судя по всему, можно закрывать.
