### ISSUE TITLE
Подключаемые файлы

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_1#7]
Опять же документация.
Все картинки, шрифты и тд должны иметь уникальное название в рамках проекта и не содержать кириллических символов. Если в проекте нет индивидуальных соглашений, то они должны именоваться в стиле lower-case-hyphenated;
Проверь названия шрифтов.

**Comment by whiteGloom** [comment]
Аа... >:{} Большие буквы) Один момент.

**Comment by whiteGloom** [comment]
Поправил шрифты и иконки.

UPD: нет, не поправил.

**Comment by whiteGloom** [comment]
Вот теперь всё правильно. Git не хотел считать изменение регистра за изменение.

**Comment by EvgeniyChuprov** [comment]
Убрать дублирующие названия шрифтов в папке fonts

**Comment by whiteGloom** [comment]
Не понял, какие именно?

UPD: я так и не нашёл дублирующихся. Или расширение больше не канает?
UPD2: Всё, нашёл. Это git опять шалит. Сейчас уберу.

**Comment by EvgeniyChuprov** [comment]
И ничего не изменилось
![image](https://user-images.githubusercontent.com/36810364/68939504-d60cf280-07b1-11ea-8665-bb0b0a24182b.png)

**Comment by whiteGloom** [comment]
Ну таки я же говорю:
![изображение](https://user-images.githubusercontent.com/36995502/68940574-1da57580-07d6-11ea-8b9c-7977fe289423.png)

Я в магазин уходил.

**Comment by whiteGloom** [comment]
Вот теперь всё должно быть хорошо.
В чём была суть проблемы: git по умолчанию не хотел считать за изменение правки в регистре наименований файлов, а когда я это исправил — git не замечал, что файлов со старым названием больше нет.
