### ISSUE TITLE
Стандарты

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_1#8]
1. Изучить и поправить по стандартом оформление - телефонов, емайл-адресов и скайп никнеймов.
2. В соответствии с пунктом 1 изучить оформление ссылок.
3.  Как давать имена классам.
4. Правила подключения шрифтов и используемые размерности шрифтов.

**Comment by whiteGloom** [comment]
Единственное - не понял претензии к размерностям шрифтов. Я, вроде, везде использую rem.
p.s ещё подключу запасной шрифт.

**Comment by whiteGloom** [comment]
Вот теперь всё должно быть хорошо. Если Вы, говоря о размерностях шрифтов, имели ввиду pt у html, то это для того, что бы rem было от чего отталкиваться.
А старые шрифты остались со времён старого описания макетов на Rizzoma. Там, вроде, говорилось и про eot и про otf.

**Comment by EvgeniyChuprov** [comment]
По поводу размерности - по моему где то видел кроме файла foundation если нет то ок. Остальное завтра посмотрю

**Comment by whiteGloom** [comment]
Я проверил через собранные стили, там нигде кроме foundation и @media для него нет других размерностей.
