### ISSUE TITLE
Мелкие правки

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_1#9]
1. Использовать var плохо загрязняет глобальную область видимости. Лучше использовать  const или если переменная изменятся то let.
2. Сейчас у тебя картинка лого сделана тегом img и ты ее передаешь объектом в блок, но картинки heder ты почему то захаркодил в css. Представь что все отображение - текст, картинки, количество шариков в skills...) прилетает с сервера одним объектом, так по сути и будет, как будешь менять картинки в хедере если прилетят новые? 
3. Почему используешь тег em и сразу переопределяешь его отображение?) Для чего он используется? Тут наверное больше подойдет какой то другой тег.
![image](https://user-images.githubusercontent.com/36810364/68941093-ec1cb200-07b5-11ea-8d4a-2f79e29a7ed1.png)

**Comment by whiteGloom** [comment]
1. Да, понимаю. Вообще это странные утверждения (это я не вам) про видимость — если функция самовызывающаяся или т.п., то область не засоряется... Так или иначе поправлю.
2. Просто спрошу (мне лень объясняться): везде img? 
3. Ну... Тут я отталкивался от информации, что em обозначает важный по смыслу текст. Мне самому эта идея не очень нравится. Это не параграф, не заголовок. Не i и не b. Хотелось как-то его семантически обозначить. Просто передавать в div как узел?

**Comment by whiteGloom** [comment]
Мисклик.

**Comment by EvgeniyChuprov** [comment]
2. да.
3. можно div
 Исправь adress -> address

**Comment by whiteGloom** [comment]
Угу.

**Comment by EvgeniyChuprov** [comment]
Удалить все неиспользуемые правила и правила, которые никак не влияют на отображение [11 пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md)

**Comment by EvgeniyChuprov** [comment]
Почему в title параметры передаешь напрямую, а не через опции миксина.
![image](https://user-images.githubusercontent.com/36810364/69512069-ae591f80-0f53-11ea-90d7-bca61ecca359.png)

**Comment by EvgeniyChuprov** [comment]
Во многих миксинах не подключен миксин title хотя там используется.
![image](https://user-images.githubusercontent.com/36810364/70370308-cd9e6800-18d6-11ea-8b69-d2b3926ea399.png)
